# image docker par défaut du pipeline => pour tous les jobs 
image: node:lts-buster-slim

test:
  tags:
    - myusine
  script:
    - npm -v

build:
  # image spécifique au job
  image: python:rc-slim-buster
  tags:
    - myusine
  script:
    - python3 -c 'print("hello")'