# image docker par défaut du pipeline => pour tous les jobs 
image: node:lts-buster-slim

# règles d'exécution du pipeline
workflow:
  # le pipeline ou le job se déclenche si au moins une règle est vraie
  # OU logique
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# liste des étapes d'exécution des jobs
stages:
  - testing
  - building
  - deploying

test:
  stage: testing
  tags:
    - myusine
  script:
    - npm -v
  rules:
    # ==, !=, pour les regex =~, !~
    # une règle est vraie si toutes ses clauses sont vraies
    # ET logique
    - if: $CI_COMMIT_BRANCH =~ /feature[0-9]+/
      changes:
        - "*.md"

build:
  stage: building
  # image spécifique au job
  # image: python:rc-slim-buster
  tags:
    - myusine
  script:
    - node -e 'console.log("Hi")'
  rules:
    - if: $CI_COMMIT_BRANCH =~ /feature[0-9]+/


deploy:
  stage: deploying
  tags:
    - myusine
  script:
    - echo "Deploy"
  rules:
    - if: $CI_COMMIT_TAG
      when: manual
